USE [master]
GO

/****** Object:  Database [DataBoomDB]    Script Date: 19.02.2022 22:08:19 ******/
CREATE DATABASE [DataBoomDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataBoomDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DataBoomDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DataBoomDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DataBoomDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataBoomDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataBoomDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataBoomDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataBoomDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataBoomDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataBoomDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataBoomDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataBoomDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataBoomDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataBoomDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataBoomDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataBoomDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataBoomDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataBoomDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataBoomDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataBoomDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataBoomDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataBoomDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataBoomDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataBoomDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataBoomDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataBoomDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataBoomDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataBoomDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataBoomDB] SET  MULTI_USER 
GO

ALTER DATABASE [DataBoomDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataBoomDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataBoomDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataBoomDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataBoomDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataBoomDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DataBoomDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DataBoomDB] SET  READ_WRITE 
GO


